package c3po.custom

import java.util.List
import java.util.Set

import com.petpet.c3po.api.model.Element
import com.petpet.c3po.api.model.helper.MetadataRecord
import com.petpet.c3po.api.model.helper.MetadataRecord.Status
import com.petpet.c3po.api.model.Source
import com.petpet.c3po.adaptor.rules.drools.LogCollector
import com.petpet.c3po.dao.MetadataUtil

global com.petpet.c3po.adaptor.rules.drools.LogCollector logger;
global java.lang.Integer loglevel;


/**
  * If Exiftool reports on author, ignore others, because Exiftool is correct
 */
rule "if Exiftool reports on authors, ignore others"
        salience 190
    when
        $e : Element()
        $mdGoodAuthor : MetadataRecord(
            status=="CONFLICT",
            property.id == "author",
            MetadataUtil.isFromTool(this, "Exiftool")
        ) from $e.metadata
        $mdBadAuthor : MetadataRecord(
            status=="CONFLICT",
            property.id == "author",
            ! MetadataUtil.isFromTool(this, "Exiftool")
        ) from $e.metadata


    then
        logger.log(loglevel,"author string issue: ");       
        logger.logMetadataRecord(loglevel,$mdBadAuthor);
	logger.logMetadataRecordValue(loglevel,$mdBadAuthor);
        
        

        modify ($e) {
            ignoreMetadata($mdBadAuthor)
        }
        logger.log(loglevel,"    -> ignore "+$mdBadAuthor);

end
