package c3po.custom

import com.petpet.c3po.api.model.Element
import com.petpet.c3po.api.model.helper.MetadataRecord
import com.petpet.c3po.dao.MetadataUtil

global com.petpet.c3po.adaptor.rules.drools.LogCollector logger;
global java.lang.Integer loglevel;



/**
 * Treat sampling_frequency_unit : 'no absolute unit of measurement' from Jhove as "none"
 */
rule "set sampling_frequency_unit : 'no absolute unit of measurement' from Jhove to 'none'"
        salience 160
    when 
        $e : Element()
        $md : MetadataRecord(
            property.id == "sampling_frequency_unit",
            value == "no absolute unit of measurement",
            MetadataUtil.isFromTool(this, "Jhove")
        ) from $e.metadata

    then
        logger.log(loglevel,"Jhove sampling_frequency_unit issue: ");
        logger.logMetadataRecord(loglevel,$md);
        
        String newValue = "None";
        $md.setValue(newValue);
        modify ($e) {
            getId()
        }
        logger.log(loglevel,"    -> set format_version to \""+newValue+"\"!");
end
