package c3po.custom

import java.util.List
import java.util.Set

import com.petpet.c3po.api.model.Element
import com.petpet.c3po.api.model.helper.MetadataRecord
import com.petpet.c3po.api.model.helper.MetadataRecord.Status
import com.petpet.c3po.api.model.Source
import com.petpet.c3po.adaptor.rules.drools.LogCollector
import com.petpet.c3po.dao.MetadataUtil

global com.petpet.c3po.adaptor.rules.drools.LogCollector logger;
global java.lang.Integer loglevel;

/**
 * set RTF format to Rich Text Format
 */
rule "set RTF format to Rich Text Format"
        salience 160
    when 
        $e : Element()
        $mdFormat : MetadataRecord(
            property.id == "format",
            value == "RTF"
        ) from $e.metadata
        $mdMime : MetadataRecord(
            property.id == "mimetype",
            value matches ".*(text|application)/rtf.*"
        ) from $e.metadata

    then
        logger.log(loglevel,"RTF format string issue: ");
        logger.logMetadataRecord(loglevel,$mdFormat);
        
        $mdFormat.setValue("Rich Text Format");
        modify ($e) {
            getId()
        }
        logger.log(loglevel,"    -> set format to \"Rich Text Format\"!");
        
end
